name: CI

on: [push]

jobs:
  check_skip_ci:
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "CI was skipped"
  
  update_gamepack:
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Install Groovy
      run: |
        sudo apt-get install groovy
    - name: Deploy gamepack
      run: |
        REPO=$(echo ${{ github.repository }} | sed "s:.*/::")
        BRANCH=$(echo ${{ github.ref }} | sed "s:.*/::")
        
        git remote rm origin
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.actor }}/${REPO}.git"
        git config user.name ${{ github.actor }}
        git config user.email noreply@${{ github.actor }}.noreply.github.com
        
        OSRS_REV=$(groovy OSRSDownloader.groovy)
        
        git add .
        git diff-index --quiet HEAD || git commit -am "Added ${OSRS_REV}.jar [skip ci]" && git push origin HEAD:${BRANCH}
